### ISSUE TITLE
User Story - Login Dependent Navbar

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#10]
<h3>Child of: </h3>

- #8  

<hr>
<br>

As a **user** I can **see different nav links depending on my login state** so that **I can see only the relevant nav links I need, and links such as 'login' are removed if I am logged in**

# Acceptance Criteria
- Navbar changes depending on user login state
- Login links replaced with Logout links for logged in users
- Register links do not appear to logged in users

# Tasks
- [x] Add user_logged_in check to views.py
- [x] Add login-check to base.html using Jinja templating
- [x] Alter HTML to show/hide necessary nav links

**Comment by LewisMDillon** [comment]
Added login checks to HTML and changed visible links depending on user's login status
