### ISSUE TITLE
User Story - Extra Site Navigation Buttons

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#11]
Child of [**EPIC - Site Viewing & Navigation**](https://github.com/users/LewisMDillon/projects/5/views/1?query=is%3Aopen+sort%3Aupdated-desc&pane=issue&itemId=40059434)

As a **user** I can **use buttons on site pages to bring me back/forward a step or bring me to a specific page** so that **when on an area of the site which naturally leads to or follows on from another specific site page, I can click a button provided to take me there.**

# Acceptance Criteria
- Nav buttons bring user to intended destination
- Nav buttons appear in all circumstances where they are useful
- Nav buttons are clearly labelled, and their destination is clear to the user

# Tasks
- [ ] Create default button HTML & CSS
- [ ] Implement buttons on any page where they are useful
- [ ] Add correct button URLs

**Comment by LewisMDillon** [comment]
Created default class and styles for site buttons. Implemented one on homepage. Will add more where needed as the site progresses. User Story is completed as this button can now be placed on any page with ease
