### ISSUE TITLE
User Story - Product Prices

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#13]
<h3>Child of: </h3>

- #12 

<hr>
<br>

As a **user** I can **see prices of all products** so that **I have an accurate measure of the costs of all products that I view**

# Acceptance Criteria
- Accurate prices displayed on all products
- Prices are uniform across users' basket and at checkout
- Prices are correctly summed to give user a total cost at checkout

# Tasks
- [x] Add HTML for product price display
- [x] Set price field in product's entry in Product Model
- [x] Create logic for summing product costs

**Comment by LewisMDillon** [comment]
All prices now viewable and accurate. Prices sum together correctly
