### ISSUE TITLE
User Story - Card Payments

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#14]
<h3>Child of: </h3>

- #12 

<hr>
<br>

As a **user** I can **use my credit/debit card to pay for products** so that **I can use the online payment system on the site and receive my products, without dealing with cash payments**

# Acceptance Criteria
- Front-end form allows users to enter their card details
- Card details are checked for validation, and user is informed if they entered details incorrectly
- Card details are kept secure throughout the payment process
- Extra validation prompts, such as card issuer validation prompts, appear if necessary.

# Tasks
- [x] Link site with Stripe
- [x] Import Stripe card payment form into HTML
- [x] Test Stripe payments

**Comment by LewisMDillon** [comment]
Stripe payments implemented, test cards working successfully with orders created in database and events created on Stripe website.
