### ISSUE TITLE
User Story - Order Number Creation

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#15]
<h3>Child of: </h3>

- #12 

<hr>
<br>

As an **admin** I can **create orders & order numbers for user purchases** so that **orders can be organised & stored correctly, and reviewed if need be**

# Acceptance Criteria
- Order numbers are created upon user purchase
- Order numbers are linked correctly with orders and stored in the database
- User can see their order number after purchase

# Tasks
- [x] Create Order model with unique order numbers
- [x] Add logic to create an Order object upon user order
- [x] Insert order number into order confirmation HTML

**Comment by LewisMDillon** [comment]
Order model exists, order objects are successfully created upon order creation. Order numbers are displayed to the user at checkout page
