### ISSUE TITLE
User Story - Payment Process Security - Webhooks

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#16]
<h3>Child of: </h3>

- #12 

<hr>
<br>

As an **admin** I can **initialise a secure chain of payment processes** so that **users cannot accidentally or intentionally interrupt the processing of their payment or their order creation after it has been initialised**

# Acceptance Criteria
- Payment processing and order creation cannot be interrupted by user input
- Webhooks used to create chain of secure events
- Database is manipulated correctly, even if user closes or refreshes the page during payment processing
- Users' orders are completed correctly and they receive an order number and email

# Tasks
- [x] Create webhooks.py & webhook handler.py
- [x] Import stripe code
- [x] Add code for webhook handlers
- [x] Test webhooks in stripe

**Comment by LewisMDillon** [comment]
Webhooks created and implemented, Webhooks returning correct response on Stripe
