### ISSUE TITLE
User Story - Purchase Confirmation Emails

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#17]
<h3>Child of: </h3>

- #12 

<hr>
<br>

As a **user** I can **receive purchase confirmation emails** so that **I have confirmation of my order, and a record of my purchase and important order information**

# Acceptance Criteria
- Emails are sent to user's email upon purchase
- Emails contain list of items purchased and price paid
- Emails contain the purchase's unique order number

# Tasks
- [x] Create default email content
- [x] Add order number to email
- [x] Add order items to email
- [x] Add sendmail function to  views.py to automatically send emails to users' provided address

**Comment by LewisMDillon** [comment]
Added send mail function to webhook handler - emails to be sent on order success. Created template for confirmation emails
