### ISSUE TITLE
User Story - Product List

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#23]
Child of [**EPIC - Site Products**](https://github.com/users/LewisMDillon/projects/5/views/1?query=is%3Aopen+sort%3Aupdated-desc&pane=issue&itemId=40333633)

As a **user** I can **see and interact with a list of products available on the site**

# Acceptance Criteria
- All products are listed
- Product list accurately reflects product database objects
- User can click on products to view details
- User can add products to their basket

# Tasks
- [ ] Create view and URL for product list
- [ ] Link view to product model
- [ ] Create view and URL for product detail view
- [ ] Create HTML for product list and product detail
- [ ] Add 'add to basket' buttons and link functionality to basket

**Comment by LewisMDillon** [comment]
Created product (Our Courses) page and linked it to the product model. Page successfully shows details of products

**Comment by LewisMDillon** [comment]
Added product detail page and linked product list page products to their respective detail pages
