### ISSUE TITLE
User Story - Product Database

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#24]
Child of [**EPIC - Site Products**](https://github.com/users/LewisMDillon/projects/5/views/1?query=is%3Aopen+sort%3Aupdated-desc&pane=issue&itemId=40333633)

As an **admin** I can **create/read/update/delete products in a back-end database** so that **I have control over what products exist and are displayed for purchase on the site**

# Acceptance Criteria
- Product model exists with all necessary fields
- Product model has full CRUD functionality
- Product model can be interacted with using a front-end form

# Tasks
- [ ] Create product model in models.py
- [ ] Plan out and implement all necessary fields in product model
- [ ] Create form for front-end interactivity with product model
- [ ] Create URL & View for front-end form

**Comment by LewisMDillon** [comment]
Created product model and category model

**Comment by LewisMDillon** [comment]
New epic was created for front-end product updating as its scope was too large for a User Story
