### ISSUE TITLE
User Story - Product Search & Sort

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#25]
<h3>Child of: </h3>

- #22 

<hr>
<br>

As a **user** I can **search for and sort products** so that **I can easily find the most suitable product for my needs**

# Acceptance Criteria
- User can search for products
- Search returns relevant products
- User is informed if search returns nothing
- Products can be sorted by their attributes including name, category, date-added, price

# Tasks
- [x] Add HTML & CSS for search box
- [x] Create HTML search form and return searches to view
- [x] Create search & filter functionality in view using Q module
- [x] Add sorting links to products page
- [x] Add sorting & ordering functionality to product view

**Comment by LewisMDillon** [comment]
Added searchbox, nav links, and sorting links to product page
