### ISSUE TITLE
User Story - Subscription Payments

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#26]
<h3>Child of: </h3>

- #12 

<hr>
<br>

As a **user** I can **sign up to a subscription-based payment model** so that **I can access all of the site content for a lower upfront fee**

# Acceptance Criteria
- Users can sign up to subscription based model
- Subscription based model is well advertised on site
- Subscription is offered as alternative where relevant
- Subscription payments recur to users' card successfully
- Users gain access to content upon signing up

# Tasks
- [ ] Implement subscription payment in Stripe
- [ ] Create HTML for subscription info on various site pages
- [ ] Create user groups in Django admin to allow subscribers to access certain content

**Comment by LewisMDillon** [comment]
This story will not be included in this deploymentt
