### ISSUE TITLE
User Story - Custom Error Pages

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#27]
<h3>Child of: </h3>

- #8  

<hr>
<br>

As a **user** I can **see common error pages with user friendly messages and site-related styling** so that **I can more accurately understand why I have reached an error page, can still see all site related styling and have an option to return to the homepage**

# Acceptance Criteria
- User sees custom error page when site throws a common error
- Custom error page lists the error code
- Custom error page has a user-friendly message
- Custom error page has easy option to return home

# Tasks
- [x] Create custom error handlers for common errors (400, 403, 404, 500)
- [x] Create HTML for custom error pages
- [x] Create URLs for custom error pages
- [x] Create buttons for redirecting user back to homepage

**Comment by LewisMDillon** [comment]
Added custom error templates and custom error handler functionality
