### ISSUE TITLE
User Story - Contact Form

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#29]
As a **user** I can **use a contact form** so that **I can easily send a message to the site admin if I have a question or a concern**.

# Acceptance Criteria
- Contact form exists and visible on front end
- Contact form has a linked model in back-end database
- Contact form submission creates database object in relevant model
- Database object created contains all user information provided
- User is informed that their contact form was submitted successfully

# Tasks
- [ ] Create database model for contact form submissions
- [ ] Create form & link it to back-end database model
- [ ] Create HTML for contact page
- [ ] Create success message for user feedback upon submission

**Comment by LewisMDillon** [comment]
Added contact page on front end and linked it to backend contact model.

Also created a view for staff to view/edit/delete contact requests. On this same page, contact messages can be updated to be marked as responded to or not responded to.
