### ISSUE TITLE
User Story - Password Handling & Recovery

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#3]
<h3>Child of: </h3>

- #1 

<hr>
<br>

As an **admin** I can **hash & securely store users' passwords** so that **users' sensitive information remains secure**

# Acceptance Criteria
- Users are asked to confirm passwords at point of registration
- Passwords are automatically hashed and never stored as plaintext
- Users can use their password to access their account
- Users can recover their password if they forget it

# Tasks
- [x] Create password confirmation input in registration form
- [x] Link form to Django's backend which will hash passwords
- [x] Add Django's built-in password recovery

**Comment by LewisMDillon** [comment]
Using Django built in password handling, passwords are automatically hashed. Allauth provides email password recovery as standard.
