### ISSUE TITLE
User Story - Newsletter Database

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#32]
<h3>Child of: </h3>

- #30 

<hr>
<br>

As an **admin** I can **store user emails** so that **I can send them the site newsletter**

# Acceptance Criteria
- Newsletter model exists in site backend with relevant fields
- User signup to newsletter creates model objects automatically
- Users who unsubscribe from newsletter have their email removed from the database

# Tasks
- [x] Create database model
- [x] Link model to newsletter signup forms/boxes
- [x] Link model to unsubscribe forms

**Comment by LewisMDillon** [comment]
Added unsubscribe function to delete entries from newsletter model
