### ISSUE TITLE
User Story - Newsletter Emails

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#33]
<h3>Child of: </h3>

- #30 

<hr>
<br>

As an **admin** I can **send the site newsletter to signed-up users** so that **I can inform them of news and updates about the site**

# Acceptance Criteria
- Site newsletter can be sent to all email addresses in newsletter database model
- Newsletter is created from an email template and is editable on site frontend
- Newsletter email contains site links, as well as link to unsubscribe

# Tasks
- [ ] Create sendmail functionality in views
- [ ] Create email template for newsletter
- [ ] Add links to newsletter email for users to unsubscribe

**Comment by LewisMDillon** [comment]
This user story will not be included in this deployment.
