### ISSUE TITLE
User Story - Profile Model

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#42]
<h3>Child of: </h3>

- #34 

<hr>
<br>

As an **admin** I can **keep an organised databse of user profiles** so that **user profiles can be created and saved to the backend of the site.**

# Acceptance Criteria
- Profile model exists
- Profile model is linked to user model
- Profile objects have full CRUD functionality

# Tasks
- [x] Create Profile app
- [x] Create Profile model
- [x] Add appropriate model fields including foreign key to user model
- [x] Register profile model in database

**Comment by LewisMDillon** [comment]
Profile model created and is working correctly
