### ISSUE TITLE
User Story - Profile Page

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#45]
<h3>Child of: </h3>

- #34 

<hr>
<br>

As a **user** I can **see and edit my profile page** so that **my profile details are viewable, and I can change them to match any changes in my information**

# Acceptance Criteria
- Users can visit their profile page via a nav link
- Users see their current information listed on their page
- Users can edit their information using a front-end form
- Users can see a list of their previous orders on their profile page
- Users cannot see/edit other users' profiles

# Tasks
- [x] Create template and HTML for profile page
- [x] Link profile page to correct urls
- [x] Create form for users to edit their information
- [x] Import users' order history
- [x] Add a check to see if user owns the profile, otherwise disable the page

**Comment by LewisMDillon** [comment]
Profile page now exists, no information imported to the profile as of yet

**Comment by LewisMDillon** [comment]
Profile page now contains users' information & order history. Profile URL is inaccessible by other users as intended.
