### ISSUE TITLE
User Story - User Profiles

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#5]
<h3>Child of: </h3>

- #1 

<hr>
<br>

# Acceptance Criteria
- Profiles are created automatically upon user registration
- Profiles display users' relevant information
- Profile details are editable by user
- Users may only edit their own profile and cannot see other users' sensitive information

# Tasks
- [ ] Create HTML for user profiles
- [ ] Create Profile model
- [ ] Create Django signal for automatic profile creation on register
- [ ] Create Profile form for user editing & link it to profile model
- [ ] Add restriction in Views.py to disallow users from editing other profiles & viewing sensitive info

**Comment by LewisMDillon** [comment]
The scope of this issue is beyond a single user story. A User Profile Epic has been created in its place:

- #34
