### ISSUE TITLE
User Story - Registration Validation Emails

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#6]
<h3>Child of: </h3>

- #1 

<hr>
<br>

As an **admin** I can **send confirmation emails to registering users** so that **My registration process is more secure, and I validate all user emails when they register**

# Acceptance Criteria
- User receive an email to their provided email address
- Users can easily click a link in the email to validate their account

# Tasks
- [x] Add the email validation step into the registration procedure
- [ ] Create text content for validation email template
- [x] Update Settings.py to use our email settings
- [x] Log emails to console for testing

**Comment by LewisMDillon** [comment]
Allauth sends these emails as standard
