### ISSUE TITLE
User Story - User Login & Logout

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#7]
<h3>Child of: </h3>

- #1 

<hr>
<br>

As a **user** I can **log in & out of my account** so that **I can see my profile and access login-only areas of the site, as well as log out to keep my account secure**

# Acceptance Criteria
- Users can successfully log in & out of their existing account
- Users can use the details they provided at registration to log in

# Tasks
- [x] Create HTML for login/logout pages
- [x] Create Views & URL's for login/logout pages
- [x] Create login form on front end

**Comment by LewisMDillon** [comment]
Allauth provides this functionality as standard
