### ISSUE TITLE
User Story - Navbar & Links

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/web-piano-academy#9]
<h3>Child of: </h3>

- #8  

<hr>
<br>

As a **user** I can **navigate around the site using links in a navbar** so that **I can easily access any area of the site I wish to see**

# Acceptance Criteria
- Navbar appears on all site pages
- Site Logo takes user to homepage
- Navbar links take user to expected page
- Navbar links are well organised with dropdowns if necessary
- Navbar is responsive and links stay visible and usable on all screen sizes

# Tasks
- [x] Create Nav element in base.html
- [x] Import Bootstrap responsive nav element
- [x] Add links to all site page URLs
- [x] Organise links into groups with Bootstrap dropdowns

**Comment by LewisMDillon** [comment]
Created navbar in base.html with links to all existing site pages including allauth account pages

**Comment by LewisMDillon** [comment]
Added links to all pages, added styling, added user login checks and login dependent links.
